### ISSUE TITLE
[BUG]: `anvil-zksync` fails on `ubuntu-latest` due to missing `libssl.so.1.1`

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/anvil-zksync#524]
#### 📝 Description

When executing the `anvil-zksync` binary for `x86_64-unknown-linux-gnu` on **`ubuntu-latest` (Ubuntu 22.04)**, the following error occurs:

```
anvil-zksync: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

The issue stems from the binary being dynamically linked to `libssl.so.1.1`, which is not available in `ubuntu-latest` due to the migration to OpenSSL 3. The binary works correctly on **Ubuntu 20.04**, where `libssl1.1` is still supported, but fails on newer systems.

This creates compatibility issues when trying to use `anvil-zksync` in CI pipelines.

#### 🔄 Steps to Reproduce

1. Download the `x86_64-unknown-linux-gnu` binary from the `v0.2.2` release.
2. Run the binary on an Ubuntu 22.04 (or `ubuntu-latest`) machine:
   ```bash
   ./anvil-zksync
   ```
3. Observe the error:
   ```
   anvil-zksync: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
   ```

For easier reproduction, use the `anvil-zksync-action` in a GitHub Actions workflow. The branch `db/update-for-v0.2.2` just has additional logs for debugging. 

Here's an example:

#### 🔧 Example Workflow

```yaml
name: run

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  tests:
    name: Compatibility Test
    strategy:
      matrix:
        platform: [ubuntu-20.04, ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run anvil-zksync
        uses: dutterbutter/anvil-zksync-action@db/update-for-v0.2.2
        with:
          mode: run
          log: info
          logFilePath: anvil_zksync.log
          target: x86_64-unknown-linux-gnu
          releaseTag: v0.2.2
```

#### 🤔 Expected Behavior

The `anvil-zksync` binary should start up correctly without requiring `libssl1.1`, regardless of the underlying OS version.

#### 😯 Current Behavior

The binary fails with the following error on Ubuntu 22.04 (or `ubuntu-latest`):

```
anvil-zksync: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

#### 🖥️ Environment Details

- **Binary Version**: `v0.2.2` (x86_64-unknown-linux-gnu)
- **Rust Version**: [e.g., rustc 1.52.0]
- **Operating System**: 
  - **Works**: Ubuntu 20.04
  - **Fails**: Ubuntu 22.04 (or `ubuntu-latest`)

#### 📋 Additional Context

The issue appears to be related to the [Cross.toml](https://github.com/matter-labs/anvil-zksync/blob/main/Cross.toml) configuration. The `pre-build` section for `x86_64-unknown-linux-gnu` installs `libssl-dev`, which defaults to `libssl1.1` in older environments but is no longer available on newer systems (Ubuntu 22.04+).

To resolve this, the binary should:
1. Be **statically linked** to OpenSSL to avoid runtime dependencies on `libssl.so`.
2. Alternatively, provide a version compatible with OpenSSL 3 (`libssl3`) for modern environments.

#### 📎 Logs and Debug Output

Relevant output from the failing environment:

```
anvil-zksync: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```
